#!/bin/bash
source /opt/gemstone/product/seaside/defSeaside

# check for the license key
if [ -s $GEMSTONE/seaside/etc/gemstone.secret ]; then
      . $GEMSTONE/seaside/etc/gemstone.secret
else
      echo 'Missing password file $GEMSTONE/seaside/etc/gemstone.secret'
      exit 1
 fi

echo "Starting stone: $GEMSTONE_NAME"

setuidgid DAEMONTOOLS_USER $GEMSTONE/seaside/bin/stopGemstone $GEMSTONE_CURATOR_PASS

exec setuidgid DAEMONTOOLS_USER fghack $GEMSTONE/bin/startstone $GEMSTONE_NAME -z $GEMSTONE_SYS_CONF -l $GEMSTONE_LOGDIR/$GEMSTONE_NAME.log
