#!/bin/bash
source /opt/gemstone/product/seaside/defSeaside
$GEMSTONE/bin/waitstone $GEMSTONE_NAME 2
# Create the stats directory if it's not there
mkdir -p /home/DAEMONTOOLS_USER/stats/1-second
chown -R DAEMONTOOLS_USER:DAEMONTOOLS_USER /home/DAEMONTOOLS_USER/stats
cd /home/DAEMONTOOLS_USER/stats/1-second
exec setuidgid DAEMONTOOLS_USER fghack $GEMSTONE/bin/statmonitor $GEMSTONE_NAME -rAzq -h 1 -i 1
