#!/bin/bash
source /opt/gemstone/product/seaside/defSeaside
export GEMSTONE_NRS_ALL='#dir:$GEMSTONE_DATADIR#log:/$GEMSTONE_LOGDIR/%N%P.log'

export GEMSTONE_SYS_CONF=$GEMSTONE_DATADIR/system.conf
export GEMSTONE_EXE_CONF=$GEMSTONE_DATADIR

exec setuidgid DAEMONTOOLS_USER  fghack $GEMSTONE/bin/startnetldi -g -a DAEMONTOOLS_USER -n -l $GEMSTONE_LOGDIR/gs64ldi.log -P 50377
